### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by bzerangue** [thedodobird2/contentful-hugo#1]
I have been looking for something like this. For a Go novice, how do I use this with Hugo?

**Comment by thedodobird2** [comment]
Thanks for the interest. It's not quite done yet but the first usable version should be done by next week. I will update the readme with instructions by then.

PS: you won't really need much Go knowledge :)

**Comment by bzerangue** [comment]
Oh great! Thank you for the reply! Looking forward to try it out soon.
